name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        data: [ ["56-fpm", "5.6-fpm"], ["70-fpm", "7.0-fpm"], ["71-fpm", "7.1-fpm"], ["72-fpm", "7.2-fpm"], ["73-fpm", "7.3-fpm"], ["74-fpm", "7.4-fpm"], ["80-fpm", "8.0-fpm"], ["81-fpm", "8.1-fpm"] ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          FILE_IDENTIFIER: ${{ matrix.data[0] }}
          TAG_NAME: ${{ matrix.data[1] }}
        run: |
          set -eux
          docker build -f ./Dockerfile-$FILE_IDENTIFIER -t $DOCKER_ORGANIZATION/base-php:$TAG_NAME .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push $DOCKER_ORGANIZATION/base-php:$TAG_NAME
